// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Roy Situmorang",
            "email": "roy.situmorang@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/languages": {
            "get": {
                "description": "finding languages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "Finding languages",
                "operationId": "FindLanguages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Language"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/verses": {
            "get": {
                "description": "finding verses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verse"
                ],
                "summary": "Finding verses",
                "operationId": "FindVerses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Version code",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BookName chapterNo:verseNoStart-verseNoEnd",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Passage"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/versions/{uid}": {
            "get": {
                "description": "finding version by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Version"
                ],
                "summary": "Finding version by UID",
                "operationId": "FindVersion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Version UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Version"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_roysitumorang_bible_modules_book_model.Book": {
            "type": "object",
            "properties": {
                "chapters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roysitumorang_bible_modules_book_model.Chapter"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "07pz6q6qc0c2s"
                },
                "name": {
                    "type": "string",
                    "example": "Genesis"
                }
            }
        },
        "github_com_roysitumorang_bible_modules_book_model.Chapter": {
            "type": "object",
            "properties": {
                "link": {
                    "type": "string",
                    "example": "http://localhost:18000/v1/verses?q=Genesis+1\u0026version=KJ21"
                },
                "number": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "helper.Response": {
            "type": "object",
            "properties": {
                "app": {
                    "type": "string",
                    "example": "bible"
                },
                "data": {},
                "latency": {
                    "type": "string",
                    "example": "7.746177ms"
                },
                "message": {
                    "type": "string",
                    "example": ""
                },
                "request_id": {
                    "type": "string",
                    "example": "add11106-20af-40c2-becb-d1a063e00e77"
                },
                "request_url": {
                    "type": "string",
                    "example": "GET http://localhost:18000/v1/languages"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                },
                "status_code": {
                    "type": "integer",
                    "example": 200
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-02-06T16:44:47.444931371+07:00"
                }
            }
        },
        "model.Language": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "EN"
                },
                "id": {
                    "type": "string",
                    "example": "07pz6q6q80c2q"
                },
                "name": {
                    "type": "string",
                    "example": "English"
                },
                "versions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Version"
                    }
                }
            }
        },
        "model.Passage": {
            "type": "object",
            "properties": {
                "book": {
                    "type": "string",
                    "example": "Genesis"
                },
                "chapter": {
                    "type": "integer",
                    "example": 1
                },
                "verse_end": {
                    "type": "integer",
                    "example": 20
                },
                "verse_start": {
                    "type": "integer",
                    "example": 1
                },
                "verses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Verse"
                    }
                }
            }
        },
        "model.Verse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "In the beginning God created the heaven and the earth."
                },
                "book": {
                    "type": "string",
                    "example": "Genesis"
                },
                "chapter_no": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "string",
                    "example": "07py2kdcg0004"
                },
                "verse_no": {
                    "type": "integer",
                    "example": 1
                },
                "version": {
                    "type": "string",
                    "example": "KJ21"
                }
            }
        },
        "model.Version": {
            "type": "object",
            "properties": {
                "books": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_roysitumorang_bible_modules_book_model.Book"
                    }
                },
                "code": {
                    "type": "string",
                    "example": "KJ21"
                },
                "id": {
                    "type": "string",
                    "example": "07pz6q6q80c2r"
                },
                "name": {
                    "type": "string",
                    "example": "21st Century King James Version"
                },
                "slug": {
                    "type": "string",
                    "example": "21st-Century-King-James-Version-KJ21-Bible"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Bible API",
	Description:      "This is documentation of Bible API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
